/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsSplatRouteImport } from './routes/threads/$'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces/$spaceId'
import { Route as SpacesSpaceIdWidgetsSplatRouteImport } from './routes/spaces/$spaceId/widgets/$'
import { Route as SpacesSpaceIdThreadsSplatRouteImport } from './routes/spaces/$spaceId/threads/$'
import { Route as SpacesSpaceIdRecordsSplatRouteImport } from './routes/spaces/$spaceId/records/$'
import { Route as SpacesSpaceIdDocumentsSplatRouteImport } from './routes/spaces/$spaceId/documents/$'
import { Route as SpacesSpaceIdDocsSplatRouteImport } from './routes/spaces/$spaceId/docs/$'
import { Route as SpacesSpaceIdRecordsCollectionIdRecordIdRouteImport } from './routes/spaces/$spaceId/records/$collectionId/$recordId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsSplatRoute = ThreadsSplatRouteImport.update({
  id: '/threads/$',
  path: '/threads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdWidgetsSplatRoute =
  SpacesSpaceIdWidgetsSplatRouteImport.update({
    id: '/widgets/$',
    path: '/widgets/$',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdThreadsSplatRoute =
  SpacesSpaceIdThreadsSplatRouteImport.update({
    id: '/threads/$',
    path: '/threads/$',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdRecordsSplatRoute =
  SpacesSpaceIdRecordsSplatRouteImport.update({
    id: '/records/$',
    path: '/records/$',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdDocumentsSplatRoute =
  SpacesSpaceIdDocumentsSplatRouteImport.update({
    id: '/documents/$',
    path: '/documents/$',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)
const SpacesSpaceIdDocsSplatRoute = SpacesSpaceIdDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdRecordsCollectionIdRecordIdRoute =
  SpacesSpaceIdRecordsCollectionIdRecordIdRouteImport.update({
    id: '/records/$collectionId/$recordId',
    path: '/records/$collectionId/$recordId',
    getParentRoute: () => SpacesSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/threads/$': typeof ThreadsSplatRoute
  '/spaces/$spaceId/docs/$': typeof SpacesSpaceIdDocsSplatRoute
  '/spaces/$spaceId/documents/$': typeof SpacesSpaceIdDocumentsSplatRoute
  '/spaces/$spaceId/records/$': typeof SpacesSpaceIdRecordsSplatRoute
  '/spaces/$spaceId/threads/$': typeof SpacesSpaceIdThreadsSplatRoute
  '/spaces/$spaceId/widgets/$': typeof SpacesSpaceIdWidgetsSplatRoute
  '/spaces/$spaceId/records/$collectionId/$recordId': typeof SpacesSpaceIdRecordsCollectionIdRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/threads/$': typeof ThreadsSplatRoute
  '/spaces/$spaceId/docs/$': typeof SpacesSpaceIdDocsSplatRoute
  '/spaces/$spaceId/documents/$': typeof SpacesSpaceIdDocumentsSplatRoute
  '/spaces/$spaceId/records/$': typeof SpacesSpaceIdRecordsSplatRoute
  '/spaces/$spaceId/threads/$': typeof SpacesSpaceIdThreadsSplatRoute
  '/spaces/$spaceId/widgets/$': typeof SpacesSpaceIdWidgetsSplatRoute
  '/spaces/$spaceId/records/$collectionId/$recordId': typeof SpacesSpaceIdRecordsCollectionIdRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/threads/$': typeof ThreadsSplatRoute
  '/spaces/$spaceId/docs/$': typeof SpacesSpaceIdDocsSplatRoute
  '/spaces/$spaceId/documents/$': typeof SpacesSpaceIdDocumentsSplatRoute
  '/spaces/$spaceId/records/$': typeof SpacesSpaceIdRecordsSplatRoute
  '/spaces/$spaceId/threads/$': typeof SpacesSpaceIdThreadsSplatRoute
  '/spaces/$spaceId/widgets/$': typeof SpacesSpaceIdWidgetsSplatRoute
  '/spaces/$spaceId/records/$collectionId/$recordId': typeof SpacesSpaceIdRecordsCollectionIdRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/spaces/$spaceId'
    | '/threads/$'
    | '/spaces/$spaceId/docs/$'
    | '/spaces/$spaceId/documents/$'
    | '/spaces/$spaceId/records/$'
    | '/spaces/$spaceId/threads/$'
    | '/spaces/$spaceId/widgets/$'
    | '/spaces/$spaceId/records/$collectionId/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/spaces/$spaceId'
    | '/threads/$'
    | '/spaces/$spaceId/docs/$'
    | '/spaces/$spaceId/documents/$'
    | '/spaces/$spaceId/records/$'
    | '/spaces/$spaceId/threads/$'
    | '/spaces/$spaceId/widgets/$'
    | '/spaces/$spaceId/records/$collectionId/$recordId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/spaces/$spaceId'
    | '/threads/$'
    | '/spaces/$spaceId/docs/$'
    | '/spaces/$spaceId/documents/$'
    | '/spaces/$spaceId/records/$'
    | '/spaces/$spaceId/threads/$'
    | '/spaces/$spaceId/widgets/$'
    | '/spaces/$spaceId/records/$collectionId/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRouteWithChildren
  ThreadsSplatRoute: typeof ThreadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$': {
      id: '/threads/$'
      path: '/threads/$'
      fullPath: '/threads/$'
      preLoaderRoute: typeof ThreadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/widgets/$': {
      id: '/spaces/$spaceId/widgets/$'
      path: '/widgets/$'
      fullPath: '/spaces/$spaceId/widgets/$'
      preLoaderRoute: typeof SpacesSpaceIdWidgetsSplatRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/threads/$': {
      id: '/spaces/$spaceId/threads/$'
      path: '/threads/$'
      fullPath: '/spaces/$spaceId/threads/$'
      preLoaderRoute: typeof SpacesSpaceIdThreadsSplatRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/records/$': {
      id: '/spaces/$spaceId/records/$'
      path: '/records/$'
      fullPath: '/spaces/$spaceId/records/$'
      preLoaderRoute: typeof SpacesSpaceIdRecordsSplatRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/documents/$': {
      id: '/spaces/$spaceId/documents/$'
      path: '/documents/$'
      fullPath: '/spaces/$spaceId/documents/$'
      preLoaderRoute: typeof SpacesSpaceIdDocumentsSplatRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/docs/$': {
      id: '/spaces/$spaceId/docs/$'
      path: '/docs/$'
      fullPath: '/spaces/$spaceId/docs/$'
      preLoaderRoute: typeof SpacesSpaceIdDocsSplatRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/records/$collectionId/$recordId': {
      id: '/spaces/$spaceId/records/$collectionId/$recordId'
      path: '/records/$collectionId/$recordId'
      fullPath: '/spaces/$spaceId/records/$collectionId/$recordId'
      preLoaderRoute: typeof SpacesSpaceIdRecordsCollectionIdRecordIdRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
  }
}

interface SpacesSpaceIdRouteChildren {
  SpacesSpaceIdDocsSplatRoute: typeof SpacesSpaceIdDocsSplatRoute
  SpacesSpaceIdDocumentsSplatRoute: typeof SpacesSpaceIdDocumentsSplatRoute
  SpacesSpaceIdRecordsSplatRoute: typeof SpacesSpaceIdRecordsSplatRoute
  SpacesSpaceIdThreadsSplatRoute: typeof SpacesSpaceIdThreadsSplatRoute
  SpacesSpaceIdWidgetsSplatRoute: typeof SpacesSpaceIdWidgetsSplatRoute
  SpacesSpaceIdRecordsCollectionIdRecordIdRoute: typeof SpacesSpaceIdRecordsCollectionIdRecordIdRoute
}

const SpacesSpaceIdRouteChildren: SpacesSpaceIdRouteChildren = {
  SpacesSpaceIdDocsSplatRoute: SpacesSpaceIdDocsSplatRoute,
  SpacesSpaceIdDocumentsSplatRoute: SpacesSpaceIdDocumentsSplatRoute,
  SpacesSpaceIdRecordsSplatRoute: SpacesSpaceIdRecordsSplatRoute,
  SpacesSpaceIdThreadsSplatRoute: SpacesSpaceIdThreadsSplatRoute,
  SpacesSpaceIdWidgetsSplatRoute: SpacesSpaceIdWidgetsSplatRoute,
  SpacesSpaceIdRecordsCollectionIdRecordIdRoute:
    SpacesSpaceIdRecordsCollectionIdRecordIdRoute,
}

const SpacesSpaceIdRouteWithChildren = SpacesSpaceIdRoute._addFileChildren(
  SpacesSpaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRouteWithChildren,
  ThreadsSplatRoute: ThreadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
