/** Kept with the tool implementation so examples use the same public contract. */
export const DRAWING_GUIDE = `Drawings are ordinary Worktable documents with a visual editing surface.

Find: worktable_documents_read action list lists every format; drawing format id is worktable.quickdraw. Use the returned extensionless path. Search finds titles and typed labels, not the meaning of freehand strokes. Shared worktable_documents_write handles move, archive, restore, checkpoint and restore_version; worktable_delete action document deletes a whole drawing. Raw read_source/replace remain available for exact source round trips.

General preview: worktable_documents_read action render accepts spaceId, path, optional expectedRevision and preview {theme,width}. HTML uses the same generic action with optional viewport height, fullPage, CSS-pixel clip and timeoutMs. PNG bytes arrive as image content, not a URL or base64 text.

Read: worktable_drawings_read action inspect returns sourceRevision, stable object ids, geometry, text, bounds and a PNG image by default. Inspect the actual image before interpreting freehand marks, overlap or spatial relationships. query filters by ids, text, types and intersecting region {x,y,w,h}; offset/limit paginate results, and nextOffset signals more. query omits images by default. render returns an image using the managed preview browser (no open user window is needed): preview {format:'png'|'svg',theme:'light'|'dark',region,ids,width,background,labels}. Top-level region filters structured objects and supplies the default crop; preview.region only crops the image. render omits the structured object list. labels:true overlays short numbers with an ID map in preview.labels. PNG is an MCP image block; SVG is an embedded text resource. Clients that cannot display embedded resources should request PNG. Preview metadata identifies the same sourceRevision as the returned objects. versionId reads a retained historical version. changes lists retained agent batches with readable summaries, affected addedIds/changedIds/removedIds and changeId for undo/redo. Summaries include short label examples, including before/after labels for renames. Each affected-ID list contains up to 100 IDs; counts and affectedIdsTruncated identify larger batches. Use inspect with versionId equal to changeId for the retained resulting drawing. undoAvailable means the required history is retained; later conflicting edits can still prevent undo.

Create: worktable_drawings_write action create takes spaceId, path, title, requestId and operations. Each add uses a simple object, for example:
{"action":"create","spaceId":"demo","path":"request-flow","title":"Request flow","requestId":"flow-create-1","operations":[{"op":"add","ref":"browser","object":{"type":"rectangle","x":0,"y":0,"width":180,"height":90,"text":"Browser"}},{"op":"add","ref":"api","object":{"type":"rectangle","x":300,"y":0,"width":180,"height":90,"text":"API","color":"blue"}},{"op":"add","object":{"type":"arrow","startBinding":{"shapeId":"browser","anchor":"right"},"endBinding":{"shapeId":"api","anchor":"left"}}}]}
The references result maps temporary refs to stable ids. Later operations in the same batch may reference earlier refs. Coordinates are world pixels; rotation is radians. Arrows use a start x/y and local endpoint delta dx/dy. Arrows and lines can attach endpoints with startBinding/endBinding: {shapeId,anchor}. shapeId accepts a stable ID or an earlier batch ref; anchor is top/right/bottom/left/center (default start:right, end:left). Attached endpoints follow target movement, size and rotation in both tools and canvas. Set a binding to null to detach that endpoint. Removing a target detaches its endpoints at their current positions. Direct connector geometry edits detach existing bindings unless supplied again; duplicated connectors start detached. Attachments use bounding-box anchors, not obstacle routing or outline snapping. Agents choose placement; there is no automatic layout.

Edit: inspect first, then action edit with expectedRevision equal to sourceRevision, a new requestId and operations. Use update {id,changes:{text,color,...}}, move {id,x,y}, resize {id,width,height}, rotate {id,rotation}, duplicate {id,ref,x,y}, reorder {id,position:'front'|'back'}, remove {id}, or title {title}. Geometry types are rectangle, ellipse, triangle, diamond, hexagon, star; also text, note, arrow, line, draw, highlight and image. Sizes s/m/l/xl and fonts draw/sans/serif/mono use sensible defaults. Notes resize proportionally by width; their height follows content, so omit height. Read summaries use the same text/width/height names as writes. Draw/highlight points are local x,y,pressure triples. import_image {ref,width,height,dataUrl} embeds a bounded PNG/JPEG/WebP/GIF; add an image object with assetId set to that ref. Remote URLs and SVG image imports are unsupported. New or changed image bytes must decode successfully before saving, even with preview.mode none; each dimension is limited to 8192 pixels and stored images total at most 16 million pixels. Native PNG captures browser-decoded PNG/JPEG/WebP/GIF assets as a still image.

Verify: writes return a PNG preview of the resulting snapshot by default. preview.mode can be all, changed (crop to affected objects), or none. To check a proposal without saving, set previewOnly:true on create/edit; then send the same operations with a NEW requestId to save. Proposal previews have kind=proposal and sourceRevision identifies the base revision (null for a new document), not a saved proposal. Added object IDs can change on save; use the final references mapping. Validation is atomic: invalid operations leave the document unchanged. On stale revision, inspect again and adapt; do not blindly retry against a new revision. On connection loss retry the SAME requestId and identical input; retained receipts prevent duplicate writes. A saved result with preview.status='failed' or 'unavailable' means the edit succeeded: retry render, not the edit. Native PNG uses Quickdraw's Canvas rendering and shared local fonts, including multilingual fallbacks and color emoji. Font coverage is finite; inspect the image and diagnostics. SVG remains a legacy exporter with limited fonts and visual differences; native PNG is the visual reference. The managed sandboxed browser must be installed and runnable; geometry-dependent edits and new/changed image imports fail before saving when it is unavailable. Very large scenes and raster images have resource limits.

Undo: use action undo with the specific changeId, latest expectedRevision and a new requestId. Only the principal that authored the batch can undo or redo it. It reverses that batch only, preserving unrelated later changes. Conflicting changes to affected objects/title refuse the undo. Redo references the undo batch's returned changeId and uses the same conflict checks. Creation undo removes created objects; it does not delete the document. Receipts and reversibility expire with retained document history; use shared checkpoints for long-lived recovery. Whole-version restore replaces the whole document and is distinct from targeted undo.

Permissions: drawing reads need documents:read; drawing writes need both documents:read and documents:write. A permission denial requires an authorized connection/token, not a different tool workaround.\n`
