// Generated by scripts/generate-theme.ts. Do not edit by hand.
export const DRAWING_THEME = {
  "light": {
    "id": "light",
    "background": "#f3f5f7",
    "colors": {
      "black": {
        "stroke": "#283440",
        "fill": "#e7eaee",
        "note": "#eee4bb"
      },
      "grey": {
        "stroke": "#6b7683",
        "fill": "#e7eaee",
        "note": "#e2e6eb"
      },
      "light-violet": {
        "stroke": "#9b79aa",
        "fill": "#eee6f2",
        "note": "#e4d5ea"
      },
      "violet": {
        "stroke": "#80569a",
        "fill": "#e9dfef",
        "note": "#d9c5e4"
      },
      "blue": {
        "stroke": "#4263bd",
        "fill": "#e0e7f5",
        "note": "#cdd9f0"
      },
      "light-blue": {
        "stroke": "#528aae",
        "fill": "#e1ecf3",
        "note": "#cce0ec"
      },
      "yellow": {
        "stroke": "#a27c32",
        "fill": "#f1e9d5",
        "note": "#eaddb7"
      },
      "orange": {
        "stroke": "#b07142",
        "fill": "#f1e4d8",
        "note": "#e8ceb7"
      },
      "green": {
        "stroke": "#3d8069",
        "fill": "#dfebe5",
        "note": "#c8dfd2"
      },
      "light-green": {
        "stroke": "#689052",
        "fill": "#e6eddc",
        "note": "#d6e3c5"
      },
      "light-red": {
        "stroke": "#b77478",
        "fill": "#f1e2e3",
        "note": "#e8ced0"
      },
      "red": {
        "stroke": "#b94e50",
        "fill": "#f0dddd",
        "note": "#e6c3c3"
      }
    },
    "noteText": "#283440",
    "selection": "#4263bd",
    "selectionFill": "rgba(66, 99, 189, 0.09)",
    "handleFill": "#f3f5f7",
    "scribble": "#db6065",
    "grid": {
      "line": {
        "minor": "rgba(40, 52, 64, 0.09)",
        "major": "rgba(40, 52, 64, 0.17)"
      },
      "dot": {
        "minor": "rgba(40, 52, 64, 0.17)",
        "major": "rgba(40, 52, 64, 0.29)"
      }
    }
  },
  "dark": {
    "id": "dark",
    "background": "#17191d",
    "colors": {
      "black": {
        "stroke": "#e1e5ea",
        "fill": "#2f343b",
        "note": "#d8cda7"
      },
      "grey": {
        "stroke": "#a0aab6",
        "fill": "#2b3037",
        "note": "#ced4dc"
      },
      "light-violet": {
        "stroke": "#c0a1cf",
        "fill": "#39323f",
        "note": "#d5bddf"
      },
      "violet": {
        "stroke": "#b28dc8",
        "fill": "#352c3e",
        "note": "#c5acd4"
      },
      "blue": {
        "stroke": "#8ba5ed",
        "fill": "#293449",
        "note": "#beccec"
      },
      "light-blue": {
        "stroke": "#8bb8d4",
        "fill": "#293943",
        "note": "#bed7e6"
      },
      "yellow": {
        "stroke": "#d5b779",
        "fill": "#40392c",
        "note": "#dfd0a4"
      },
      "orange": {
        "stroke": "#d4a17d",
        "fill": "#403329",
        "note": "#e0c2a9"
      },
      "green": {
        "stroke": "#86bca4",
        "fill": "#293b33",
        "note": "#b5d2c2"
      },
      "light-green": {
        "stroke": "#a6c18a",
        "fill": "#333d2b",
        "note": "#cbdab6"
      },
      "light-red": {
        "stroke": "#d2a0a3",
        "fill": "#403034",
        "note": "#dfbfc1"
      },
      "red": {
        "stroke": "#db9092",
        "fill": "#402c30",
        "note": "#dfb4b5"
      }
    },
    "noteText": "#283440",
    "selection": "#8ba5ed",
    "selectionFill": "rgba(139, 165, 237, 0.12)",
    "handleFill": "#202329",
    "scribble": "#db6065",
    "grid": {
      "line": {
        "minor": "rgba(225, 229, 234, 0.09)",
        "major": "rgba(225, 229, 234, 0.17)"
      },
      "dot": {
        "minor": "rgba(225, 229, 234, 0.17)",
        "major": "rgba(225, 229, 234, 0.29)"
      }
    }
  }
} as const
