import targets from "./generation-targets.json"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

import {
  THEME_MODES,
  themeConfig,
  type ThemeMode,
} from "../packages/ui/src/theme/theme-config.ts"

const root = join(import.meta.dir, "..")
const generatedNote =
  "Generated by scripts/generate-theme.ts. Do not edit by hand."

function getModeVariables(mode: ThemeMode): Record<string, string> {
  const colors = themeConfig.modes[mode]
  const accents = Object.fromEntries(
    Object.entries(themeConfig.accents).map(([name, values]) => [
      name,
      values[mode],
    ])
  ) as Record<keyof typeof themeConfig.accents, string>
  const status = Object.fromEntries(
    Object.entries(themeConfig.status).map(([name, values]) => [
      name,
      values[mode],
    ])
  ) as Record<keyof typeof themeConfig.status, string>
  const inlineCode = themeConfig.content.inlineCode[mode]

  return {
    background: colors.canvas,
    foreground: colors.foreground,
    "reading-foreground": colors.readingForeground,
    card: colors.panel,
    "card-foreground": colors.foreground,
    popover: colors.overlay,
    "popover-foreground": colors.foreground,
    primary: accents.primary,
    "primary-foreground": colors.contrastForeground,
    "primary-text": accents.primaryText,
    secondary: colors.muted,
    "secondary-foreground": colors.secondaryForeground,
    muted: colors.muted,
    "muted-foreground": colors.mutedForeground,
    "resize-handle": colors.resizeHandle,
    accent: colors.decorative,
    "accent-foreground": colors.secondaryForeground,
    "surface-tint": colors.decorative,
    "surface-selected": colors.selected,
    destructive: status.destructive,
    border: colors.border,
    input: colors.borderInput,
    "input-hover": colors.borderInputHover,
    ring: accents.focusRing,
    success: status.success,
    warning: status.warning,
    info: status.info,
    sidebar: colors.sidebar,
    "sidebar-desktop": colors.sidebarDesktop,
    "sidebar-foreground": colors.sidebarForeground,
    "sidebar-space-foreground": `color-mix(in oklch, ${colors.sidebarForeground} ${themeConfig.sidebar.spaceForegroundOpacity}, transparent)`,
    "sidebar-item-foreground": `color-mix(in oklch, ${colors.sidebarForeground} ${themeConfig.sidebar.itemForegroundOpacity}, transparent)`,
    "sidebar-primary": accents.primary,
    "sidebar-primary-foreground": colors.contrastForeground,
    "sidebar-hover": colors.sidebarHover,
    "sidebar-accent": colors.sidebarAccent,
    "sidebar-control": colors.sidebarControl,
    "sidebar-control-border": colors.sidebarControlBorder,
    "sidebar-accent-foreground": colors.sidebarAccentForeground,
    "control-active": colors.controlActive,
    "sidebar-border": colors.borderChrome,
    "sidebar-ring": accents.focusRing,
    "scrollbar-thumb": colors.scrollbarThumb,
    "scrollbar-thumb-hover": colors.scrollbarThumbHover,
    "border-chrome": colors.borderChrome,
    "overlay-border": colors.overlayBorder,
    "accent-bronze": accents.bronze,
    "accent-bronze-ink": accents.bronzeInk,
    "code-accent-foreground": accents.technicalInk,
    "code-accent-background": `color-mix(in oklch, ${accents.technical} ${inlineCode.surfaceMix}, transparent)`,
    "illustration-accent": accents.illustration,
    "well-bg": colors.field,
    "well-hover-bg": colors.fieldHover,
    "grid-line": themeConfig.backdrop[mode].lineColor,
    "grid-wash": themeConfig.backdrop[mode].washColor,
    "glow-primary": accents.primaryGlow,
    "key-face-top": themeConfig.finishes[mode].primaryFaceTop,
    "key-face-bottom": themeConfig.finishes[mode].primaryFaceBottom,
    "key-highlight": themeConfig.finishes[mode].primaryHighlight,
    "key-edge-primary": themeConfig.finishes[mode].primaryEdge,
    "key-shadow": themeConfig.finishes[mode].primaryShadow,
    "key-shadow-ambient": themeConfig.finishes[mode].primaryAmbientShadow,
    "overlay-floating-shadow": themeConfig.elevation[mode].floatingShadow,
    "overlay-dialog-shadow": themeConfig.elevation[mode].dialogShadow,
    "overlay-drawer-top-shadow": themeConfig.elevation[mode].drawerShadowTop,
    "overlay-drawer-right-shadow":
      themeConfig.elevation[mode].drawerShadowRight,
    "overlay-drawer-bottom-shadow":
      themeConfig.elevation[mode].drawerShadowBottom,
    "overlay-drawer-left-shadow": themeConfig.elevation[mode].drawerShadowLeft,
    "dialog-backdrop": themeConfig.elevation[mode].dialogBackdrop,
    "navigation-surface": themeConfig.elevation[mode].navigationSurface,
    "navigation-backdrop": themeConfig.elevation[mode].navigationBackdrop,
    "navigation-drawer-shadow": themeConfig.elevation[mode].navigationShadow,
  }
}

function renderMode(mode: ThemeMode): string {
  const lines = Object.keys(getModeVariables(mode)).map(
    (cssName) => `  --${cssName}: var(--theme-${mode}-${cssName});`
  )
  themeConfig.charts[mode].forEach((_, index) => {
    lines.push(
      `  --chart-${index + 1}: var(--theme-${mode}-chart-${index + 1});`
    )
  })
  lines.push("  --accent-bronze-soft: var(--surface-tint);")
  lines.push(`  --grid-size: ${themeConfig.backdrop.gridSize}px;`)
  lines.push(`  --grid-fade-width: ${themeConfig.backdrop.fadeWidth};`)
  lines.push(`  --grid-fade-height: ${themeConfig.backdrop.fadeHeight};`)
  lines.push(`  --grid-fade-midpoint: ${themeConfig.backdrop.fadeMidpoint};`)
  lines.push(
    `  --grid-fade-mid-opacity: ${themeConfig.backdrop.fadeMidOpacity};`
  )
  lines.push(`  --grid-fade-tail: ${themeConfig.backdrop.fadeTail};`)
  lines.push(
    `  --grid-fade-tail-opacity: ${themeConfig.backdrop.fadeTailOpacity};`
  )
  lines.push(`  --grid-fade-stop: ${themeConfig.backdrop.fadeStop};`)
  lines.push("  --grid-left-origin: 0% 100%;")
  lines.push("  --grid-right-origin: 100% 100%;")
  lines.push(`  --sidebar-item-radius: ${themeConfig.sidebar.itemRadius};`)
  lines.push(`  --field-shadow: ${themeConfig.finishes.fieldShadow};`)
  lines.push(
    `  --field-focus-shadow: 0 0 0 3px color-mix(in oklch, var(--ring) ${themeConfig.finishes[mode].fieldFocusOpacity}, transparent);`
  )
  lines.push(
    `  --dialog-background-clip: ${themeConfig.elevation[mode].dialogBackgroundClip};`
  )
  lines.push(
    `  --outline-button-shadow: ${themeConfig.finishes.outlineButtonShadow};`
  )
  lines.push(
    `  --outline-button-image: ${themeConfig.finishes.outlineButtonImage};`
  )
  return lines.join("\n")
}

function renderPrimitiveAliases(): string {
  const lines: string[] = []
  for (const mode of THEME_MODES) {
    for (const [cssName, value] of Object.entries(getModeVariables(mode))) {
      lines.push(`  --theme-${mode}-${cssName}: ${value};`)
    }
    themeConfig.charts[mode].forEach((value, index) => {
      lines.push(`  --theme-${mode}-chart-${index + 1}: ${value};`)
    })
    lines.push(
      `  --mermaid-canvas-${mode}: ${themeConfig.mermaid[mode].canvas};`
    )
  }
  return lines.join("\n")
}

export function renderThemeCss(): string {
  return `/* ${generatedNote} */
:root {
${renderPrimitiveAliases()}
}

:root,
.light,
:root[data-theme="light"] {
${renderMode("light")}
}

.dark,
:root[data-theme="dark"] {
${renderMode("dark")}
}
`
}

export function renderBlockNoteCss(): string {
  const { light, dark } = themeConfig.blockNote
  const mode = (
    name: "light" | "dark",
    values: typeof light | typeof dark
  ) => `.bn-container[data-color-scheme="${name}"] {
  --bn-colors-editor-text: ${values.editorText};
  --bn-colors-editor-background: transparent;
  --bn-colors-menu-text: ${values.text};
  --bn-colors-menu-background: ${values.menu};
  --bn-colors-tooltip-text: ${values.text};
  --bn-colors-tooltip-background: ${values.subtle};
  --bn-colors-hovered-text: ${values.text};
  --bn-colors-hovered-background: ${values.subtle};
  --bn-colors-selected-text: ${values.selectedText};
  --bn-colors-selected-background: ${values.selected};
  --bn-colors-disabled-text: ${values.disabledText};
  --bn-colors-disabled-background: ${values.subtle};
  --bn-colors-shadow: ${values.shadow};
  --bn-colors-border: ${values.border};
  --bn-colors-side-menu: ${values.disabledText};
  --bn-font-family: var(--font-sans);
  --bn-border-radius: 6px;
}`
  return `/* ${generatedNote} */
${mode("light", light)}

${mode("dark", dark)}
`
}

export function renderAuthKitCss(): string {
  const systemFont = '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'

  const modeVariables = (mode: ThemeMode) => {
    const colors = themeConfig.modes[mode]
    const finish = themeConfig.finishes[mode]

    return `  --wt-auth-canvas: ${colors.canvas};
  --wt-auth-panel: ${colors.panel};
  --wt-auth-raised: ${colors.raised};
  --wt-auth-foreground: ${colors.foreground};
  --wt-auth-muted: ${colors.mutedForeground};
  --wt-auth-selected: ${colors.selected};
  --wt-auth-decorative: ${colors.decorative};
  --wt-auth-border: ${colors.border};
  --wt-auth-input: ${colors.borderInput};
  --wt-auth-input-hover: ${colors.borderInputHover};
  --wt-auth-field: ${colors.field};
  --wt-auth-field-hover: ${colors.fieldHover};
  --wt-auth-primary: ${themeConfig.accents.primary[mode]};
  --wt-auth-primary-text: ${colors.contrastForeground};
  --wt-auth-link: ${themeConfig.accents.primaryText[mode]};
  --wt-auth-destructive: ${themeConfig.status.destructive[mode]};
  --wt-auth-ring: ${themeConfig.accents.focusRing[mode]};
  --wt-auth-field-focus-shadow: 0 0 0 3px color-mix(in oklch, var(--wt-auth-ring) ${finish.fieldFocusOpacity}, transparent);
  --wt-auth-grid-line: ${themeConfig.backdrop[mode].lineColor};
  --wt-auth-grid-wash: ${themeConfig.backdrop[mode].washColor};
  --wt-auth-key-top: ${finish.primaryFaceTop};
  --wt-auth-key-bottom: ${finish.primaryFaceBottom};
  --wt-auth-key-highlight: ${finish.primaryHighlight};
  --wt-auth-key-edge: ${finish.primaryEdge};
  --wt-auth-key-shadow: ${finish.primaryShadow};
  --wt-auth-key-ambient: ${finish.primaryAmbientShadow};
  --wt-auth-panel-shadow: ${themeConfig.elevation[mode].dialogShadow};`
  }

  return `/* ${generatedNote}
   Source of truth: packages/ui/src/theme/theme-config.ts
   Paste inside the WorkOS AuthKit Background editor. WorkOS supplies the
   outer .ak-Background rule. */

.light-theme & {
${modeVariables("light")}
}

.dark-theme & {
${modeVariables("dark")}
}

position: relative;
isolation: isolate;
overflow-x: hidden;
padding: 24px;
color: var(--wt-auth-foreground);
background: var(--wt-auth-canvas);
font-family: ${systemFont};

&::before {
  content: "";
  position: fixed;
  inset: 0;
  z-index: 0;
  pointer-events: none;
  background-image:
    linear-gradient(
      to right,
      var(--wt-auth-grid-line) 1px,
      transparent 1px
    ),
    linear-gradient(
      to bottom,
      var(--wt-auth-grid-line) 1px,
      transparent 1px
    ),
    radial-gradient(
      ellipse at 0% 100%,
      var(--wt-auth-grid-wash),
      transparent 100%
    ),
    radial-gradient(
      ellipse at 100% 100%,
      var(--wt-auth-grid-wash),
      transparent 100%
    );
  background-size:
    ${themeConfig.backdrop.gridSize}px ${themeConfig.backdrop.gridSize}px,
    ${themeConfig.backdrop.gridSize}px ${themeConfig.backdrop.gridSize}px,
    100% 100%,
    100% 100%;
  -webkit-mask-image:
    radial-gradient(
      ellipse ${themeConfig.backdrop.fadeWidth} ${themeConfig.backdrop.fadeHeight} at 0% 100%,
      black 0%,
      rgb(0 0 0 / ${themeConfig.backdrop.fadeMidOpacity}) ${themeConfig.backdrop.fadeMidpoint},
      rgb(0 0 0 / ${themeConfig.backdrop.fadeTailOpacity}) ${themeConfig.backdrop.fadeTail},
      transparent ${themeConfig.backdrop.fadeStop}
    ),
    radial-gradient(
      ellipse ${themeConfig.backdrop.fadeWidth} ${themeConfig.backdrop.fadeHeight} at 100% 100%,
      black 0%,
      rgb(0 0 0 / ${themeConfig.backdrop.fadeMidOpacity}) ${themeConfig.backdrop.fadeMidpoint},
      rgb(0 0 0 / ${themeConfig.backdrop.fadeTailOpacity}) ${themeConfig.backdrop.fadeTail},
      transparent ${themeConfig.backdrop.fadeStop}
    );
  mask-image:
    radial-gradient(
      ellipse ${themeConfig.backdrop.fadeWidth} ${themeConfig.backdrop.fadeHeight} at 0% 100%,
      black 0%,
      rgb(0 0 0 / ${themeConfig.backdrop.fadeMidOpacity}) ${themeConfig.backdrop.fadeMidpoint},
      rgb(0 0 0 / ${themeConfig.backdrop.fadeTailOpacity}) ${themeConfig.backdrop.fadeTail},
      transparent ${themeConfig.backdrop.fadeStop}
    ),
    radial-gradient(
      ellipse ${themeConfig.backdrop.fadeWidth} ${themeConfig.backdrop.fadeHeight} at 100% 100%,
      black 0%,
      rgb(0 0 0 / ${themeConfig.backdrop.fadeMidOpacity}) ${themeConfig.backdrop.fadeMidpoint},
      rgb(0 0 0 / ${themeConfig.backdrop.fadeTailOpacity}) ${themeConfig.backdrop.fadeTail},
      transparent ${themeConfig.backdrop.fadeStop}
    );
}

& > * {
  position: relative;
  z-index: 1;
}

.ak-Content {
  width: min(100%, 448px);
  gap: 0;
  padding: 32px;
  color: var(--wt-auth-foreground);
  background: color-mix(in oklch, var(--wt-auth-panel) 90%, transparent);
  border: 1px solid var(--wt-auth-border);
  border-radius: 17px;
  box-shadow: var(--wt-auth-panel-shadow);
  -webkit-backdrop-filter: blur(18px) saturate(1.08);
  backdrop-filter: blur(18px) saturate(1.08);
}

.ak-Header {
  gap: 14px;
  margin-bottom: 24px;
}

.ak-LogoIcon {
  width: 56px;
  height: 56px;
}

.ak-Logo:not(.ak-LogoIcon),
.ak-LogoImage {
  width: auto;
  max-width: 184px;
  height: 26px;
  object-fit: contain;
}

.ak-Heading {
  color: var(--wt-auth-foreground);
  font-family: "Fraunces", Georgia, "Times New Roman", serif;
  font-size: 22px;
  font-weight: 400;
  line-height: 1.18;
  letter-spacing: -0.015em;
}

.ak-Card {
  padding: 0;
  color: var(--wt-auth-foreground);
  background: transparent;
  border: 0;
  border-radius: 0;
  box-shadow: none;
  contain: none;
  overflow: visible;
  -webkit-backdrop-filter: none;
  backdrop-filter: none;
}

.ak-Card,
.ak-Card * {
  font-family: ${systemFont};
}

.ak-Card::before,
.ak-Card::after {
  display: none;
  content: none;
}

.ak-Card > p {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 4px;
  min-height: 20px;
  margin-top: 24px;
  overflow: visible;
  line-height: 20px;
}

.ak-AuthForm {
  gap: 18px;
}

.ak-Label {
  color: var(--wt-auth-foreground);
  font-size: 14px;
  font-weight: 600;
  line-height: 20px;
  letter-spacing: 0.005em;
}

.ak-TextField {
  height: 44px;
  padding: 0;
  color: var(--wt-auth-foreground);
  background: var(--wt-auth-field);
  border: 1px solid var(--wt-auth-input);
  border-radius: 12px;
  box-shadow: none;
  transition:
    background-color 150ms ease,
    border-color 150ms ease,
    box-shadow 150ms ease;
}

.ak-TextField:hover {
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-input-hover);
}

.ak-TextField:focus-within {
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-ring);
  box-shadow: var(--wt-auth-field-focus-shadow);
}

.ak-TextField input {
  height: 42px;
  padding: 0 14px;
  color: var(--wt-auth-foreground);
  font-size: 14px;
  letter-spacing: 0.015em;
}

.ak-TextField input::placeholder {
  color: var(--wt-auth-muted);
  opacity: 1;
}

.ak-PrimaryButton {
  height: 44px;
  color: var(--wt-auth-primary-text);
  background-color: var(--wt-auth-primary);
  background-image: linear-gradient(
    to bottom,
    var(--wt-auth-key-top) 0%,
    var(--wt-auth-primary) 55%,
    var(--wt-auth-key-bottom) 100%
  );
  background-clip: border-box;
  border: 1px solid transparent;
  border-radius: 12px;
  box-shadow:
    inset 0 1px 0 var(--wt-auth-key-highlight),
    0 2px 0 var(--wt-auth-key-edge),
    0 4px 7px -3px var(--wt-auth-key-shadow);
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.005em;
  transition:
    filter 120ms ease,
    transform 120ms ease,
    box-shadow 120ms ease;
}

.ak-PrimaryButton:hover {
  filter: brightness(1.025);
  transform: translateY(-1px);
  box-shadow:
    inset 0 1px 0 var(--wt-auth-key-highlight),
    0 3px 0 var(--wt-auth-key-edge),
    0 6px 9px -4px var(--wt-auth-key-shadow);
}

.ak-PrimaryButton:active {
  filter: none;
  transform: translateY(2px);
  box-shadow:
    inset 0 1px 1px var(--wt-auth-key-shadow),
    0 0 0 var(--wt-auth-key-edge),
    0 1px 2px var(--wt-auth-key-shadow);
}

.ak-PrimaryButton:focus-visible {
  outline: none;
  box-shadow:
    0 0 0 3px color-mix(in oklch, var(--wt-auth-ring) 42%, transparent),
    inset 0 1px 0 var(--wt-auth-key-highlight),
    0 2px 0 var(--wt-auth-key-edge),
    0 5px 8px -2px var(--wt-auth-key-shadow);
}

.ak-AuthButton {
  width: 100%;
  height: 44px;
  justify-content: center;
  color: var(--wt-auth-foreground);
  background: var(--wt-auth-field);
  border: 1px solid var(--wt-auth-input);
  border-radius: 12px;
  box-shadow: none;
  transition:
    background-color 150ms ease,
    border-color 150ms ease;
}

.ak-AuthButton:hover {
  color: var(--wt-auth-foreground);
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-input-hover);
}

.ak-AuthButton:focus-visible {
  outline: none;
  border-color: var(--wt-auth-ring);
  box-shadow: 0 0 0 3px color-mix(in oklch, var(--wt-auth-ring) 42%, transparent);
}

.ak-AuthMethodsProviders,
.ak-AuthMethodsProvidersRow {
  width: 100%;
}

.ak-AuthMethodsProvidersRow {
  display: grid;
  grid-template-columns: 1fr;
  gap: 10px;
}

.ak-AuthMethodsProvidersRow > div {
  display: flex !important;
  width: 100%;
}

.ak-AuthButtonLabel {
  display: inline !important;
}

.ak-AuthButtonIcon {
  flex: 0 0 auto;
}

.ak-TextSeparator {
  color: var(--wt-auth-muted);
  letter-spacing: 0.08em;
}

.ak-BackLink,
.ak-Link,
.ak-Content .BrandedLink {
  color: var(--wt-auth-link);
  text-decoration-color: color-mix(in oklch, var(--wt-auth-link) 45%, transparent);
  text-underline-offset: 3px;
}

.ak-BackLink {
  margin-top: 20px;
}

.ak-BackLink:hover,
.ak-Link:hover,
.ak-Content .BrandedLink:hover {
  text-decoration-color: currentColor;
}

.ak-Callout {
  padding: 12px 14px;
  color: var(--wt-auth-destructive);
  background: color-mix(in oklch, var(--wt-auth-destructive) 9%, transparent);
  border: 1px solid color-mix(in oklch, var(--wt-auth-destructive) 20%, transparent);
  border-radius: 12px;
}

.ak-CalloutIcon,
.ak-CalloutText {
  color: inherit;
}

.ak-Otp {
  gap: 8px;
}

.ak-OtpInput {
  width: 44px;
  height: 48px;
  color: var(--wt-auth-foreground);
  background: var(--wt-auth-field);
  border: 1px solid var(--wt-auth-input);
  border-radius: 12px;
  box-shadow: none;
}

.ak-OtpInput:hover {
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-input-hover);
}

.ak-OtpInput:focus-within {
  outline: none;
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-ring);
  box-shadow: var(--wt-auth-field-focus-shadow);
}

.ak-OrgSelection,
.ak-SelectionCardRoot {
  display: grid;
  gap: 8px;
  background: transparent;
  border: 0;
  border-radius: 0;
  box-shadow: none;
}

.ak-OrgSelectionButton,
.ak-SelectionCardButton {
  min-height: 48px;
  padding: 10px 12px;
  color: var(--wt-auth-foreground);
  background: var(--wt-auth-field);
  border: 1px solid var(--wt-auth-input);
  border-radius: 12px;
  transition:
    background-color 150ms ease,
    border-color 150ms ease;
}

.ak-OrgSelectionButton:hover,
.ak-SelectionCardButton:hover {
  background: var(--wt-auth-field-hover);
  border-color: var(--wt-auth-input-hover);
}

.ak-OrgSelectionButton:focus-visible,
.ak-SelectionCardButton:focus-visible {
  outline: none;
  border-color: var(--wt-auth-ring);
  box-shadow: 0 0 0 3px color-mix(in oklch, var(--wt-auth-ring) 42%, transparent);
}

.ak-OrgSelectionButtonIcon,
.ak-SelectionCardButtonIcon {
  color: var(--wt-auth-muted);
}

.ak-OrgSelectionButtonLabel,
.ak-SelectionCardButtonLabel {
  color: var(--wt-auth-foreground);
}

.ak-LastUsedBadge {
  color: var(--wt-auth-muted);
  background: var(--wt-auth-decorative);
  border: 1px solid var(--wt-auth-border);
  border-radius: 999px;
  box-shadow: none;
}

@media (max-width: 520px) {
  & {
    padding: 16px;
  }

  .ak-Content {
    padding: 24px;
  }

  .ak-Heading {
    font-size: 21px;
  }
}
`
}

function rgba(hex: string, alpha: number): string {
  const value = hex.slice(1)
  const r = Number.parseInt(value.slice(0, 2), 16)
  const g = Number.parseInt(value.slice(2, 4), 16)
  const b = Number.parseInt(value.slice(4, 6), 16)
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

function renderMermaidMode(mode: "light" | "dark") {
  const palette = themeConfig.mermaid[mode]
  const [surface1, surface2, surface3, surface4] = palette.surfaces
  return {
    darkMode: mode === "dark",
    background: palette.canvas,
    primaryColor: rgba(surface1, mode === "dark" ? 0.86 : 0.94),
    primaryTextColor: palette.text,
    primaryBorderColor: rgba(palette.border, 0.58),
    secondaryColor: rgba(surface2, mode === "dark" ? 0.82 : 0.94),
    secondaryTextColor: palette.text,
    secondaryBorderColor: rgba(palette.border, 0.5),
    tertiaryColor: rgba(surface3, mode === "dark" ? 0.8 : 0.94),
    tertiaryTextColor: palette.text,
    tertiaryBorderColor: rgba(palette.border, 0.46),
    lineColor: rgba(palette.line, 0.72),
    arrowheadColor: rgba(palette.line, 0.72),
    textColor: palette.text,
    mainBkg: rgba(surface1, 0.88),
    nodeBorder: rgba(palette.border, 0.52),
    clusterBkg: rgba(surface4, mode === "dark" ? 0.28 : 0.36),
    clusterBorder: rgba(palette.border, 0.3),
    edgeLabelBackground: rgba(surface1, 0.92),
    actorBkg: rgba(surface2, 0.88),
    actorTextColor: palette.text,
    actorBorder: rgba(palette.border, 0.48),
    actorLineColor: rgba(palette.border, 0.42),
    signalColor: palette.text,
    signalTextColor: palette.text,
    labelBoxBkgColor: rgba(surface2, 0.9),
    labelBoxBorderColor: rgba(palette.border, 0.44),
    labelTextColor: palette.text,
    loopTextColor: palette.text,
    activationBorderColor: rgba(palette.border, 0.42),
    activationBkgColor: rgba(surface3, 0.84),
    sequenceNumberColor: palette.mutedText,
    noteBkgColor: rgba(surface4, 0.88),
    noteTextColor: palette.bronzeText,
    noteBorderColor: rgba(palette.border, 0.44),
    radius: 12,
    strokeWidth: 1,
    useGradient: false,
  }
}

function renderMermaidCss(mode: "light" | "dark"): string {
  const palette = themeConfig.mermaid[mode]
  const [surface1, surface2, surface3, surface4] = palette.surfaces
  return `
  .node rect, .node circle, .node ellipse, .node polygon, .node path,
  .label-container, .cluster rect, .cluster circle, .cluster ellipse,
  .cluster polygon, .cluster path { filter: none !important; }
  .node rect, .node circle, .node ellipse, .node polygon, .node path,
  .label-container { stroke-width: 1.15px !important; }
  .cluster rect, .cluster circle, .cluster ellipse, .cluster polygon,
  .cluster path { stroke-width: 1px !important; stroke-opacity: 0.28 !important; }
  .edgeLabel rect, .edgeTerminals { filter: none !important; }
  .edgeLabel rect { fill-opacity: 0.92 !important; stroke: none !important; }
  .attributeBoxOdd { fill: ${surface1} !important; stroke: ${palette.border} !important; }
  .attributeBoxEven { fill: ${surface2} !important; stroke: ${palette.border} !important; }
  .relationshipLabelBox, .relationshipLabelBox rect { fill: ${surface1} !important; }
  .entityLabel, .er.entityLabel, .sequenceNumber, #sequencenumber { fill: ${palette.text} !important; }
  .note, .note rect { fill: ${surface4} !important; stroke: ${palette.border} !important; }
  .noteText, .noteText tspan { fill: ${palette.bronzeText} !important; }
  .labelBox, .activation0, .activation1, .activation2 { fill: ${surface3} !important; stroke: ${palette.border} !important; }
  .labelText, .labelText tspan, .messageText, .messageText tspan,
  .loopText, .loopText tspan { fill: ${palette.text} !important; }
  .section-root rect, .section-root circle, .section-root polygon,
  .section-root path, .section-root .background,
  .section--1 rect, .section--1 circle, .section--1 polygon,
  .section--1 path, .section--1 .background { fill: ${surface1} !important; }
  .section-0 rect, .section-0 circle, .section-0 polygon,
  .section-0 path, .section-0 .background { fill: ${surface2} !important; }
  .section-1 rect, .section-1 circle, .section-1 polygon,
  .section-1 path, .section-1 .background { fill: ${surface3} !important; }
  .section-2 rect, .section-2 circle, .section-2 polygon,
  .section-2 path, .section-2 .background { fill: ${surface4} !important; }
  .section-3 rect, .section-3 circle, .section-3 polygon,
  .section-3 path, .section-3 .background { fill: ${surface2} !important; }
  .section-root text, .section-root tspan, .section--1 text, .section--1 tspan,
  .section-0 text, .section-0 tspan, .section-1 text, .section-1 tspan,
  .section-2 text, .section-2 tspan, .section-3 text, .section-3 tspan { fill: ${palette.text} !important; }
  .section-edge--1, .section-edge-0, .section-edge-1,
  .section-edge-2, .section-edge-3 { stroke: ${palette.line} !important; }
`
}

export function renderMermaidTs(): string {
  const variables = {
    light: renderMermaidMode("light"),
    dark: renderMermaidMode("dark"),
  }
  return `// ${generatedNote}\nexport const MERMAID_CANVAS = ${JSON.stringify({ light: themeConfig.mermaid.light.canvas, dark: themeConfig.mermaid.dark.canvas }, null, 2)} as const\n\nexport const MERMAID_THEME_VARIABLES = ${JSON.stringify(variables, null, 2)} as const\n\nexport const MERMAID_THEME_CSS = ${JSON.stringify({ light: renderMermaidCss("light"), dark: renderMermaidCss("dark") }, null, 2)} as const\n`
}

export const generatedThemeOutputs = new Map([
  ["packages/ui/src/styles/theme.generated.css", renderThemeCss()],
  ["apps/web/src/styles/blocknote-theme.generated.css", renderBlockNoteCss()],
  ...targets.authKit.map((path): [string, string] => [
    path,
    renderAuthKitCss(),
  ]),
  ["packages/types/src/mermaid-theme.generated.ts", renderMermaidTs()],
])

if (import.meta.main) {
  const check = process.argv.includes("--check")
  let drifted = false
  for (const [relativePath, content] of generatedThemeOutputs) {
    const path = join(root, relativePath)
    if (check) {
      if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
        console.error(
          `${relativePath} is out of date. Run bun run generate:theme.`
        )
        drifted = true
      }
    } else {
      await Bun.write(path, content)
      console.log(`Wrote ${relativePath}`)
    }
  }

  if (drifted) process.exit(1)
}
