import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { resolve } from "node:path"

import {
  generatedThemeOutputs,
  renderAuthKitCss,
  renderBlockNoteCss,
  renderMermaidTs,
  renderThemeCss,
} from "./generate-theme"
import { themeConfig } from "../packages/ui/src/theme/theme-config"

const repoRoot = resolve(import.meta.dir, "..")

describe("theme artifact generation", () => {
  test("committed artifacts exactly match their in-memory render", async () => {
    for (const [relativePath, expected] of generatedThemeOutputs) {
      expect(await readFile(resolve(repoRoot, relativePath), "utf8")).toBe(
        expected
      )
    }
  })

  test("semantic CSS contains every supported selector and required variable", () => {
    const css = renderThemeCss()
    expect(css).toContain(":root,")
    expect(css).toContain(".light,")
    expect(css).toContain(':root[data-theme="light"]')
    expect(css).toContain(".dark,")
    expect(css).toContain(':root[data-theme="dark"]')
    for (const variable of [
      "--background",
      "--reading-foreground",
      "--card",
      "--popover",
      "--surface-tint",
      "--surface-selected",
      "--sidebar-hover",
      "--sidebar-control",
      "--sidebar-control-border",
      "--control-active",
      "--overlay-border",
      "--overlay-floating-shadow",
      "--overlay-dialog-shadow",
      "--overlay-drawer-top-shadow",
      "--overlay-drawer-right-shadow",
      "--overlay-drawer-bottom-shadow",
      "--overlay-drawer-left-shadow",
      "--dialog-backdrop",
      "--dialog-background-clip",
      "--navigation-surface",
      "--navigation-backdrop",
      "--navigation-drawer-shadow",
      "--sidebar-item-radius",
      "--grid-size",
      "--grid-fade-tail-opacity",
      "--well-bg",
      "--well-hover-bg",
      "--input-hover",
      "--field-focus-shadow",
      "--key-face-top",
      "--key-face-bottom",
      "--key-highlight",
      "--key-shadow-ambient",
      "--accent-bronze-soft",
      "--code-accent-foreground",
      "--code-accent-background",
      "--illustration-accent",
    ]) {
      expect(css).toContain(variable)
    }
  })

  test("BlockNote and Mermaid adapters are derived from canonical values", () => {
    const blockNote = renderBlockNoteCss()
    expect(blockNote).toContain(themeConfig.blockNote.light.editorText)
    expect(blockNote).toContain(themeConfig.blockNote.dark.editorText)
    expect(blockNote).toContain(themeConfig.blockNote.light.menu)
    expect(blockNote).toContain(themeConfig.blockNote.dark.selected)

    const mermaid = renderMermaidTs()
    expect(mermaid).toContain(themeConfig.mermaid.light.canvas)
    expect(mermaid).toContain(themeConfig.mermaid.dark.canvas)
    expect(mermaid).toContain('"useGradient": false')
  })

  test("AuthKit output targets the supported WorkOS states", () => {
    const css = renderAuthKitCss()

    expect(css).toContain(".light-theme & {")
    expect(css).toContain(".dark-theme & {")
    expect(css).toContain(".ak-Card {")
    expect(css).toContain(".ak-TextField:focus-within {")
    expect(css).toContain(".ak-PrimaryButton:focus-visible {")
    expect(css).toContain(".ak-Callout {")
    expect(css).toContain(".ak-OtpInput:focus-within {")
    expect(css).toContain(".ak-SelectionCardButton:focus-visible {")
    expect(css).toContain("@media (max-width: 520px)")
  })

  test("all generated files carry the do-not-edit marker", () => {
    for (const content of generatedThemeOutputs.values()) {
      expect(content).toMatch(
        /Generated by scripts\/generate-theme\.ts\. Do not edit by hand\./
      )
    }
  })
})
