import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

import sharp from "sharp"
import targets from "./generation-targets.json"

import { themeConfig } from "../packages/ui/src/theme/theme-config.ts"

const repoRoot = join(import.meta.dir, "..")
const generatedNote =
  "Generated by scripts/generate-brand-assets.ts. Do not edit by hand."

/**
 * Exact 2000x2000 optical lockup from the July 4 uploaded filled icon.
 * The mark bounds are x=338..1661.75 and y=764..1410.92, placing its
 * optical center 4.37% below the field's mathematical center.
 */
export const WORKTABLE_FILLED_ICON_MARK_PATH =
  "M1500.02 764C1589.34 764 1661.75 836.409 1661.75 925.729C1661.75 1015.05 1589.34 1087.46 1500.02 1087.46H1419.97V1249.19C1419.97 1338.51 1347.56 1410.92 1258.24 1410.92C1168.92 1410.92 1096.51 1338.51 1096.51 1249.19V1087.46H904.052V1249.19C904.052 1338.51 831.643 1410.92 742.322 1410.92C653.002 1410.92 580.594 1338.51 580.594 1249.19V1087.46H499.729C410.408 1087.46 338 1015.05 338 925.729C338 836.409 410.408 764 499.729 764H1500.02Z"

export function renderWorktableFilledIconSvg(): string {
  const brand = themeConfig.brand
  return `<svg width="2000" height="2000" viewBox="0 0 2000 2000" fill="none" xmlns="http://www.w3.org/2000/svg">
<!-- ${generatedNote} -->
<rect width="2000" height="2000" rx="1000" fill="url(#worktable-field)"/>
<path d="${WORKTABLE_FILLED_ICON_MARK_PATH}" fill="${brand.appIconMark}"/>
<defs>
<linearGradient id="worktable-field" x1="79" y1="258" x2="1782.5" y2="1961.5" gradientUnits="userSpaceOnUse">
<stop stop-color="${brand.appIconGradient.start}"/>
<stop offset="1" stop-color="${brand.appIconGradient.end}"/>
</linearGradient>
</defs>
</svg>
`
}

function renderBlueVariant(sourceRelativePath: string): string {
  const source = readFileSync(join(repoRoot, sourceRelativePath), "utf8")
  const recolored = source.replaceAll(
    'fill="white"',
    `fill="${themeConfig.brand.solidBlue}"`
  )
  if (recolored === source) {
    throw new Error(
      `${sourceRelativePath} has no neutral white fills to recolor`
    )
  }
  return recolored.replace(/(<svg[^>]*>)/, `$1\n<!-- ${generatedNote} -->`)
}

const filledIconSvg = renderWorktableFilledIconSvg()

export const generatedBrandTextOutputs = new Map<string, string>([
  ["assets/brand/worktable-icon-filled.svg", filledIconSvg],
  [
    "assets/brand/worktable-icon-bare-blue.svg",
    renderBlueVariant("assets/brand/worktable-icon-bare.svg"),
  ],
  [
    "assets/brand/worktable-wordmark-blue.svg",
    renderBlueVariant("assets/brand/worktable-wordmark.svg"),
  ],
  ...targets.favicons.map((path): [string, string] => [path, filledIconSvg]),
])

export const generatedBrandRasterSpecs = [
  { path: "plugins/worktable/assets/composer-icon.png", size: 128 },
  { path: "plugins/worktable/assets/logo.png", size: 512 },
  { path: "plugins/worktable/assets/logo-dark.png", size: 512 },
  { path: "apps/web/public/apple-touch-icon-180x180.png", size: 180 },
  { path: "apps/web/public/pwa-64x64.png", size: 64 },
  { path: "apps/web/public/pwa-192x192.png", size: 192 },
  { path: "apps/web/public/pwa-512x512.png", size: 512 },
  { path: "apps/web/public/maskable-icon-512x512.png", size: 512 },
] as const

export async function renderBrandPng(size: number): Promise<Buffer> {
  return sharp(Buffer.from(filledIconSvg))
    .resize(size, size, { fit: "fill" })
    .png()
    .toBuffer()
}

export function wrapPngAsIco(png: Buffer, size: number): Buffer {
  if (size < 1 || size > 256) {
    throw new Error(
      `ICO dimensions must be between 1 and 256, received ${size}`
    )
  }
  const header = Buffer.alloc(22)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(1, 4)
  header.writeUInt8(size === 256 ? 0 : size, 6)
  header.writeUInt8(size === 256 ? 0 : size, 7)
  header.writeUInt8(0, 8)
  header.writeUInt8(0, 9)
  header.writeUInt16LE(1, 10)
  header.writeUInt16LE(32, 12)
  header.writeUInt32LE(png.length, 14)
  header.writeUInt32LE(header.length, 18)
  return Buffer.concat([header, png])
}

export function extractPngFromIco(ico: Buffer): Buffer {
  if (
    ico.length < 22 ||
    ico.readUInt16LE(0) !== 0 ||
    ico.readUInt16LE(2) !== 1 ||
    ico.readUInt16LE(4) !== 1
  ) {
    throw new Error("Expected a single-image ICO file")
  }
  const length = ico.readUInt32LE(14)
  const offset = ico.readUInt32LE(18)
  if (offset + length > ico.length) {
    throw new Error("ICO PNG entry extends beyond the file")
  }
  return ico.subarray(offset, offset + length)
}

export async function generatedBrandBinaryOutputs(): Promise<
  Map<string, Buffer>
> {
  const outputs = new Map<string, Buffer>()
  for (const spec of generatedBrandRasterSpecs) {
    outputs.set(spec.path, await renderBrandPng(spec.size))
  }
  outputs.set(
    "apps/web/public/favicon.ico",
    wrapPngAsIco(await renderBrandPng(48), 48)
  )
  return outputs
}

async function decodedRgba(buffer: Buffer): Promise<{
  data: Buffer
  width: number
  height: number
}> {
  const decoded = await sharp(buffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  return {
    data: decoded.data,
    width: decoded.info.width,
    height: decoded.info.height,
  }
}

async function rasterMatches(path: string, expected: Buffer): Promise<boolean> {
  if (!existsSync(path)) return false
  const actualFile = readFileSync(path)
  const actual = path.endsWith(".ico")
    ? extractPngFromIco(actualFile)
    : actualFile
  const expectedPng = path.endsWith(".ico")
    ? extractPngFromIco(expected)
    : expected
  const [actualRgba, expectedRgba] = await Promise.all([
    decodedRgba(actual),
    decodedRgba(expectedPng),
  ])
  return (
    actualRgba.width === expectedRgba.width &&
    actualRgba.height === expectedRgba.height &&
    actualRgba.data.equals(expectedRgba.data)
  )
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check")
  let drifted = false

  for (const [relativePath, content] of generatedBrandTextOutputs) {
    const path = join(repoRoot, relativePath)
    if (check) {
      if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
        console.error(
          `${relativePath} is out of date. Run bun run generate:brand.`
        )
        drifted = true
      }
    } else {
      await Bun.write(path, content)
      console.log(`Wrote ${relativePath}`)
    }
  }

  for (const [relativePath, content] of await generatedBrandBinaryOutputs()) {
    const path = join(repoRoot, relativePath)
    if (check) {
      if (!(await rasterMatches(path, content))) {
        console.error(
          `${relativePath} is out of date. Run bun run generate:brand.`
        )
        drifted = true
      }
    } else {
      await Bun.write(path, content)
      console.log(`Wrote ${relativePath}`)
    }
  }

  if (drifted) process.exit(1)
}

if (import.meta.main) await main()
