import { createHash } from "node:crypto"
import { readFileSync } from "node:fs"
import { dirname, resolve } from "node:path"

const families = [
  "caveat",
  "noto-sans",
  "noto-serif",
  "noto-sans-mono",
  "noto-sans-symbols-2",
  ...[
    "arabic",
    "hebrew",
    "bengali",
    "tamil",
    "telugu",
    "kannada",
    "malayalam",
    "gujarati",
    "gurmukhi",
    "oriya",
    "sinhala",
    "thai",
    "khmer",
    "lao",
    "myanmar",
    "sc",
    "jp",
    "kr",
  ].map((script) => `noto-sans-${script}`),
  "noto-color-emoji",
]
const imports: string[] = []
const entries: string[] = []
const hash = createHash("sha256")
let bytes = 0
for (const name of families) {
  const pkg = `@fontsource/${name}`
  const weight =
    name === "noto-color-emoji" || name === "noto-sans-symbols-2"
      ? "400"
      : "500"
  const cssPath = import.meta
    .resolve(`${pkg}/${weight}.css`)
    .replace(/^file:\/\//, "")
  const css = readFileSync(cssPath, "utf8")
  hash.update(css)
  for (const block of css.matchAll(/@font-face\s*\{([^}]+)\}/g)) {
    const family = /font-family:\s*'([^']+)'/.exec(block[1]!)![1]!
    // This pinned emoji package's WOFF2 faces load but paint no glyphs in
    // Chromium. Its WOFF faces retain the working color tables.
    const format = name === "noto-color-emoji" ? "woff" : "woff2"
    const file = new RegExp(`url\\(\\./([^)]*\\.${format})\\)`).exec(
      block[1]!
    )![1]!
    const unicodeRange = /unicode-range:\s*([^;]+)/.exec(block[1]!)![1]!
    const data = readFileSync(resolve(dirname(cssPath), file))
    hash.update(data)
    bytes += data.byteLength
    const id = `${name}/${file.slice("files/".length)}`
    const variable = `font${imports.length}`
    imports.push(
      `import ${variable} from ${JSON.stringify(`${pkg}/${file}`)} with { type: "file" }`
    )
    entries.push(
      `  {id:${JSON.stringify(id)},family:${JSON.stringify(family)},weight:${JSON.stringify(weight)},unicodeRange:${JSON.stringify(unicodeRange)},url:${variable}}`
    )
  }
}
const output = `// Generated by scripts/generate-drawing-fonts.ts. Do not edit.\n${imports.join("\n")}\nimport type { DrawingFontAsset } from "./drawing-fonts"\nexport const DRAWING_FONT_VERSION = ${JSON.stringify(hash.digest("hex"))}\nexport const DRAWING_FONT_BYTES = ${bytes}\nexport const DRAWING_FONT_ASSETS: readonly DrawingFontAsset[] = [\n${entries.join(",\n")}\n]\n`
const path = new URL(
  "../packages/ui/src/lib/drawing-font-assets.generated.ts",
  import.meta.url
)
if (process.argv.includes("--check")) {
  if ((await Bun.file(path).text()) !== output)
    throw new Error(
      "Drawing font manifest is stale; run bun scripts/generate-drawing-fonts.ts"
    )
} else await Bun.write(path, output)
console.log(
  `Drawing fonts: ${imports.length} subsets, ${(bytes / 1024 / 1024).toFixed(1)} MiB`
)
