import { fileURLToPath } from "node:url"
const root = new URL("../", import.meta.url)
const result = await Bun.build({
  entrypoints: [
    fileURLToPath(
      new URL("packages/server/src/drawing-preview-client.ts", root)
    ),
  ],
  target: "browser",
  minify: true,
})
if (!result.success)
  throw new AggregateError(result.logs, "Drawing preview build failed")
const text =
  "// Generated by scripts/generate-drawing-preview.ts. Do not edit.\n" +
  (await result.outputs[0]!.text())
const destination = new URL(
  "packages/server/src/generated/drawing-preview.bundle.js",
  root
)
if (process.argv.includes("--check")) {
  if ((await Bun.file(destination).text()) !== text)
    throw new Error(
      "Drawing preview bundle is stale; run bun scripts/generate-drawing-preview.ts"
    )
} else await Bun.write(destination, text)
