import {
  readProductFontSource,
  stageProductFonts,
  verifyPackagedProductFonts,
} from "./product-fonts.ts"
import { fileURLToPath } from "node:url"
import { createHash } from "node:crypto"
import { brotliDecompressSync, gunzipSync } from "node:zlib"
import {
  cpSync,
  closeSync,
  openSync,
  readSync,
  realpathSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { createRequire } from "node:module"
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path"
import type { ReleaseTarget } from "./release-targets"

const require = createRequire(import.meta.url)
export const PREVIEW_PLAYWRIGHT_VERSION = "1.61.1"
export function previewHostPlatform(
  target: Pick<ReleaseTarget, "platform" | "arch">
): string {
  return target.platform === "darwin"
    ? `mac13${target.arch === "arm64" ? "-arm64" : ""}`
    : `ubuntu24.04-${target.arch}`
}
function files(root: string): string[] {
  return readdirSync(root, { withFileTypes: true }).flatMap((entry) => {
    const path = join(root, entry.name)
    return entry.isDirectory() ? files(path) : [path]
  })
}

/** Chromium's Linux ARM64 headless archive omits standalone notices. The full
 * browser at the same revision carries its generated credits in resources.pak. */
export function chromiumCredits(pak: Buffer): Buffer {
  if (pak.length < 18 || pak.readUInt32LE(0) !== 5)
    throw new Error("Unsupported Chromium resource pack")
  const count = pak.readUInt16LE(8)
  if (12 + (count + 1) * 6 > pak.length)
    throw new Error("Truncated Chromium resource table")
  for (let i = 0; i < count; i++) {
    const start = pak.readUInt32LE(14 + i * 6),
      end = pak.readUInt32LE(20 + i * 6)
    if (start > end || end > pak.length)
      throw new Error("Invalid Chromium resource bounds")
    let bytes = pak.subarray(start, end)
    try {
      if (bytes[0] === 0x1e && bytes[1] === 0x9b)
        bytes = Buffer.from(
          brotliDecompressSync(bytes.subarray(8), {
            maxOutputLength: 32 * 1024 * 1024,
          })
        )
      else if (bytes[0] === 0x1f && bytes[1] === 0x8b)
        bytes = Buffer.from(
          gunzipSync(bytes, { maxOutputLength: 32 * 1024 * 1024 })
        )
    } catch {
      continue
    }
    if (
      bytes
        .subarray(0, 100)
        .includes(Buffer.from("Generated by licenses.py")) &&
      bytes.includes(Buffer.from("Redistribution and use"))
    )
      return bytes
  }
  throw new Error("Matching Chromium archive has no generated credit notices")
}

/** Release-time only: normal archives carry the matching browser and JS driver. */
export async function stagePreviewRuntime(
  target: Pick<ReleaseTarget, "platform" | "arch">,
  destination: string,
  cache: string
): Promise<void> {
  const productFontsRoot = fileURLToPath(
    new URL("../apps/desktop/ui/fonts", import.meta.url)
  )
  readProductFontSource(productFontsRoot)
  const driverRoot = dirname(require.resolve("playwright-core/package.json"))
  const pkg = JSON.parse(readFileSync(join(driverRoot, "package.json"), "utf8"))
  if (pkg.version !== PREVIEW_PLAYWRIGHT_VERSION)
    throw new Error("Unreviewed preview browser driver version")
  const descriptor = JSON.parse(
    readFileSync(join(driverRoot, "browsers.json"), "utf8")
  ).browsers.find(
    (browser: { name: string }) => browser.name === "chromium-headless-shell"
  )
  const targetCache = join(cache, `${target.platform}-${target.arch}`)
  mkdirSync(targetCache, { recursive: true })
  const environment: NodeJS.ProcessEnv = {
    ...process.env,
    PLAYWRIGHT_BROWSERS_PATH: targetCache,
    PLAYWRIGHT_HOST_PLATFORM_OVERRIDE: previewHostPlatform(target),
    PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: "1", // Cross-target packaging; never changes runtime sandbox policy.
  }
  // Public release artifacts use the pinned upstream distribution endpoints.
  delete environment.PLAYWRIGHT_DOWNLOAD_HOST
  delete environment.PLAYWRIGHT_CHROMIUM_DOWNLOAD_HOST
  const child = Bun.spawn(
    [
      process.execPath,
      join(driverRoot, "cli.js"),
      "install",
      "chromium-headless-shell",
      "--no-progress",
    ],
    { env: environment, stdout: "inherit", stderr: "inherit" }
  )
  if ((await child.exited) !== 0)
    throw new Error(
      `Could not stage preview browser for ${target.platform}-${target.arch}`
    )
  const browserDirectory = readdirSync(targetCache).find(
    (name) => name === `chromium_headless_shell-${descriptor.revision}`
  )
  if (!browserDirectory)
    throw new Error(
      "Downloaded browser revision does not match the pinned driver"
    )
  const source = join(targetCache, browserDirectory)
  let supplementaryNotices:
    | { bytes: Buffer; source: Record<string, string> }
    | undefined
  if (!files(source).some((path) => /(?:LICENSE|NOTICE|CREDITS)/i.test(path))) {
    if (target.platform !== "linux" || target.arch !== "arm64")
      throw new Error("Unexpected missing browser notices for this target")
    const fullDescriptor = JSON.parse(
      readFileSync(join(driverRoot, "browsers.json"), "utf8")
    ).browsers.find((browser: { name: string }) => browser.name === "chromium")
    if (
      fullDescriptor.browserVersion !== descriptor.browserVersion ||
      fullDescriptor.revision !== descriptor.revision
    )
      throw new Error(
        "Chromium credits source differs from the preview browser revision"
      )
    const full = Bun.spawn(
      [
        process.execPath,
        join(driverRoot, "cli.js"),
        "install",
        "chromium",
        "--no-shell",
        "--no-progress",
      ],
      { env: environment, stdout: "inherit", stderr: "inherit" }
    )
    if ((await full.exited) !== 0)
      throw new Error("Could not acquire matching Chromium notices")
    const pack = files(
      join(targetCache, `chromium-${descriptor.revision}`)
    ).find((path) => path.endsWith("/resources.pak"))
    if (!pack) throw new Error("Matching Chromium resources are missing")
    const pak = readFileSync(pack),
      bytes = chromiumCredits(pak)
    supplementaryNotices = {
      bytes,
      source: {
        kind: "generated Chromium credits extracted from matching full browser",
        playwrightRevision: descriptor.revision,
        browserVersion: descriptor.browserVersion,
        platform: target.platform,
        arch: target.arch,
        resourcesSha256: createHash("sha256").update(pak).digest("hex"),
        creditsSha256: createHash("sha256").update(bytes).digest("hex"),
        archive: `https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/${descriptor.revision}/chromium-linux-arm64.zip`,
      },
    }
  }
  assemblePreviewRuntime(
    target,
    destination,
    driverRoot,
    source,
    supplementaryNotices,
    productFontsRoot
  )
}

export function assemblePreviewRuntime(
  target: Pick<ReleaseTarget, "platform" | "arch">,
  destination: string,
  driverRoot: string,
  source: string,
  supplementaryNotices?: { bytes: Buffer; source: Record<string, string> },
  productFontsRoot?: string
): void {
  const pkg = JSON.parse(readFileSync(join(driverRoot, "package.json"), "utf8"))
  if (pkg.version !== PREVIEW_PLAYWRIGHT_VERSION)
    throw new Error("Unreviewed preview browser driver version")
  const descriptor = JSON.parse(
    readFileSync(join(driverRoot, "browsers.json"), "utf8")
  ).browsers.find(
    (browser: { name: string }) => browser.name === "chromium-headless-shell"
  )
  const executable = files(source).find((path) =>
    /\/(?:chrome-headless-shell|headless_shell)$/.test(path)
  )
  if (!executable)
    throw new Error(
      "Managed preview archive has no headless browser executable"
    )
  const root = join(destination, "preview-runtime")
  rmSync(root, { force: true, recursive: true })
  mkdirSync(root, { recursive: true })
  cpSync(driverRoot, join(root, "driver"), {
    recursive: true,
    dereference: true,
  })
  cpSync(source, join(root, "browser"), { recursive: true, dereference: true })
  if (supplementaryNotices) {
    writeFileSync(
      join(root, "browser", "CHROMIUM-CREDITS.html"),
      supplementaryNotices.bytes
    )
    writeFileSync(
      join(root, "browser", "NOTICE-PROVENANCE.json"),
      JSON.stringify(supplementaryNotices.source, null, 2) + "\n"
    )
  }
  if (productFontsRoot) stageProductFonts(productFontsRoot, root)
  const digest = createHash("sha256")
    .update(readFileSync(executable))
    .digest("hex")
  const shippedFiles = files(root)
  writeFileSync(
    join(root, "manifest.json"),
    JSON.stringify(
      {
        type: "worktable.preview-runtime",
        version: 1,
        playwrightVersion: pkg.version,
        browserRevision: descriptor.revision,
        browserVersion: descriptor.browserVersion,
        platform: target.platform,
        arch: target.arch,
        executable: join("browser", relative(source, executable)),
        executableSha256: digest,
        installedBytes: shippedFiles.reduce(
          (total, path) => total + statSync(path).size,
          0
        ),
        driverSource: `https://github.com/microsoft/playwright/tree/v${pkg.version}`,
        browserSource: "https://chromium.googlesource.com/chromium/src/",
        licenses: shippedFiles
          .filter((path) => /(?:LICENSE|NOTICE|COPYING|CREDITS)/i.test(path))
          .map((path) => relative(root, path)),
      },
      null,
      2
    ) + "\n"
  )
  if (
    !existsSync(join(root, "driver", "LICENSE")) ||
    !shippedFiles.some((path) =>
      /(?:LICENSE\.headless_shell|CHROMIUM-CREDITS\.html)$/.test(path)
    )
  )
    throw new Error(
      "Managed preview runtime is missing upstream license notices"
    )
  if (productFontsRoot) verifyPreviewRuntime(root, target)
}

/** Validate extracted artifacts without executing a foreign target's browser or
 * requiring the separately supplied source font on the verification machine. */
export function verifyPreviewRuntime(
  runtimeRoot: string,
  target?: Pick<ReleaseTarget, "platform" | "arch">
): void {
  const root = realpathSync(runtimeRoot)
  const required = (path: unknown): string => {
    if (typeof path !== "string" || isAbsolute(path))
      throw new Error("Invalid preview runtime path")
    const absolute = resolve(root, path)
    if (!absolute.startsWith(root + sep))
      throw new Error("Preview runtime path escapes artifact")
    const actual = realpathSync(absolute)
    if (!actual.startsWith(root + sep) || !statSync(actual).isFile())
      throw new Error("Preview runtime file escapes artifact or is missing")
    return actual
  }
  const hash = (path: string): string => {
    const digest = createHash("sha256"),
      buffer = Buffer.alloc(1024 * 1024)
    const fd = openSync(path, "r")
    try {
      for (
        let size;
        (size = readSync(fd, buffer, 0, buffer.length, null)) > 0;
      )
        digest.update(buffer.subarray(0, size))
    } finally {
      closeSync(fd)
    }
    return digest.digest("hex")
  }
  const manifest = JSON.parse(readFileSync(required("manifest.json"), "utf8"))
  if (
    manifest.type !== "worktable.preview-runtime" ||
    manifest.version !== 1 ||
    manifest.playwrightVersion !== PREVIEW_PLAYWRIGHT_VERSION ||
    !["linux", "darwin"].includes(manifest.platform) ||
    !["x64", "arm64"].includes(manifest.arch) ||
    (target &&
      (manifest.platform !== target.platform || manifest.arch !== target.arch))
  )
    throw new Error("Preview runtime target or version mismatch")
  const executable = required(manifest.executable)
  if (
    !(statSync(executable).mode & 0o111) ||
    hash(executable) !== manifest.executableSha256
  )
    throw new Error("Preview browser executable permission or hash mismatch")
  for (const path of [
    "driver/index.js",
    "driver/lib/bootstrap.js",
    "driver/lib/coreBundle.js",
    "driver/lib/utilsBundle.js",
    "driver/LICENSE",
    "driver/NOTICE",
    "driver/ThirdPartyNotices.txt",
  ])
    required(path)
  const driver = JSON.parse(
    readFileSync(required("driver/package.json"), "utf8")
  )
  const descriptor = JSON.parse(
    readFileSync(required("driver/browsers.json"), "utf8")
  ).browsers?.find(
    (entry: { name: string }) => entry.name === "chromium-headless-shell"
  )
  if (
    driver.version !== PREVIEW_PLAYWRIGHT_VERSION ||
    descriptor?.revision !== manifest.browserRevision ||
    descriptor?.browserVersion !== manifest.browserVersion
  )
    throw new Error("Preview driver and browser identity mismatch")
  if (
    !Array.isArray(manifest.licenses) ||
    !manifest.licenses.includes("driver/LICENSE") ||
    !manifest.licenses.some(
      (path: unknown) =>
        typeof path === "string" &&
        path.startsWith("browser/") &&
        /(?:LICENSE\.headless_shell|CHROMIUM-CREDITS\.html)$/.test(path)
    )
  )
    throw new Error("Preview runtime license inventory is incomplete")
  for (const path of manifest.licenses) required(path)
  if (manifest.licenses.includes("browser/CHROMIUM-CREDITS.html")) {
    const provenance = JSON.parse(
      readFileSync(required("browser/NOTICE-PROVENANCE.json"), "utf8")
    )
    if (
      provenance.playwrightRevision !== manifest.browserRevision ||
      provenance.browserVersion !== manifest.browserVersion ||
      provenance.platform !== manifest.platform ||
      provenance.arch !== manifest.arch ||
      provenance.creditsSha256 !==
        hash(required("browser/CHROMIUM-CREDITS.html"))
    )
      throw new Error("Chromium credits provenance mismatch")
  }
  for (const path of [
    "fonts/manifest.json",
    "fonts/general-sans-variable.woff2",
    "fonts/GeneralSans-LICENSE.txt",
  ])
    required(path)
  verifyPackagedProductFonts(root)
}

if (import.meta.main) {
  const releaseRoot = process.argv[2]
  if (!releaseRoot)
    throw new Error(
      "Usage: bun scripts/preview-runtime.ts <extracted-release-root>"
    )
  const target = JSON.parse(
    readFileSync(join(releaseRoot, "manifest.json"), "utf8")
  )
  verifyPreviewRuntime(join(releaseRoot, "preview-runtime"), target)
}
